baseurl = "http://madewithdrew.com/blog"
languageCode = "en-us"
title = "Made with Drew"
pygmentsuseclasses = true

[params]
  Subtitle = "Recovering JavaScript developer"
  GithubID = "drewwells"
  TwitterID = "coldfuser"
  AnalyticsID = "UA-2783646-2"
  Summary = true  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
