baseurl = "https://blog.madewithdrew.com"
languageCode = "en-us"
title = "Made with Drew"
pygmentsuseclasses = true
disqusShortname = "drewwells"
googleAnalytics = "UA-2783646-2"

[params]
  Subtitle = "Go enthusiast"
  GithubID = "drewwells"
  TwitterID = "coldfuser"
  AnalyticsID = "UA-2783646-2"
  Summary = true  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
